name: Automated Deployment

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
