name: Github Action Research

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Publish to RubyGems
      run: echo "ENV_TEST : ${{secrets.ENV_TEST}}"
