name: Github Action Research

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
    - name: Hello world action
      with: # Set the secret as an input
        super_secret: ${{ secrets.SuperSecret }}
      env: # Or as an environment variable
        super_secret: ${{ secrets.SuperSecret }}

    - name: Checkout
      uses: actions/checkout@main
      
    - name: Publish to RubyGems
      run: |
        example-command "$env:SUPER_SECRET"
